### ISSUE TITLE
Propuestas y Consideraciones a tener en cuenta

### ISSUE THREAD

**Issue by Agustin-Zabalgoitia** [IvanOAn/Turismo-en-la-Tierra-Media-#5]
Estuve revisando un poco el código y anoté unas cuantas cosas a tener en cuenta, diganme sus opiniones así lo vamos ordenando:

En la clase Atracciones
- ¿Cuándo una atracción es igual a otra? ¿Cuándo el nombre es el mismo, o cuando todos los valores son iguales?

En la clase Usuario
- ¿El itinerario convendría hacerlo un list, un map, o un set?
- Los setters hasta ahora, solo se utilizan dentro de la misma clase Usuario, por lo que pueden ser eliminados y reemplazados por "this.atributo =" donde corresponda.
- El nombre promocionValida() causa confusión ya que pide una promocion y devuelve si alguna atracción ya se encuentra en el itinerario del usuario. El nombre de la función da a entender que devolverá verdadero si la promoción es válida para el usuario (el usuario tiene dinero y tiempo suficiente). Se recomienda cambiar el nombre a algo más descriptivo como "atraccionExistente()" o "promocionExistente()" para reflejar lo obtenido por el método.

En la clase Promocion
- ¿Tiene sentido guardar el cupo dentro de promoción?, eso se puede delegar en Atraccion para no tener que cambiar el cupo de la atracción y de la promoción todo el tiempo.
- En caso de que la promoción ya no sea válida porque alguna de sus atracciones ya no tenga cupo, ¿qué pasa con ella?¿se elimina del programa?
- ¿Es necesario guardar el precio de una promoción en la clase Promocion?
- ¿Las atracciones incluidas convendría hacerlo un list, un map, o un set?
- En caso de que se cambie el precio y el cupo en la clase, será necesario modificar la función promocionesDisponibles()
- Ver si es necesario que las promociones se comparen y modificar su compareTo.

**Comment by FelipeLuisMorales** [comment]
Atracciones:
- Para mi hay que compararlas por el nombre porque es lo unico que tienen realmente como distintivo, salvo que les pongamos algo asi como un ID.
Usuario:
-El itinerario creo que podria ser un set porque solo nos interesa saber el hecho de que tiene tal atraccion en su itinerario
Promocion:
-Los cambios que haria en promocion son dejarle solo el tiempo requerido, el tipo de atraccion y las atracciones incluidas(eso en la clase padre) y despues que cada tipo de promocion tenga su campo especifico como en absoluta el precio total por ej. Y a mi tambien me parece lo mejor dejar que de esas cosas se encargue directamente atraccion.
-Cuando nos de que una promocion ya no tiene cupo la podemos eliminar de la lista tranquilamente porque ya no nos sirve para nada.
-Por ahora no encuentro sentido a comparar promociones(siempre teniendo en cuenta que en el archivo no tendremos duplicados).

**Comment by IvanOAn** [comment]
Clase Atracciones:

- Yo creo que hay que ordenar las atracciones segun lo que pide el enunciado y no hay necesidad de compararlas por igual si el archivo de entrada no tiene duplicados.  Si el archivo de entrada tendría duplicados tendriamos que decidir que hacer, si tomar los datos de la ultima vez que aparece esa atraccion o la primera.

Clase Usuario:

- Coincido con Felipe, tendría que ser un Set el itinerario porque un usuario no puede aceptar dos veces la misma atracción y capaz conviene que sea un HashSet, ya que al momento de ofrecerle a un usuario una promocion hay que ver que no tenga una de las atracciones incluidas en su intinerario, y es mas rapido el HashSet que el TreeSet.

Clase Promocion:

- Yo creo que conviene tener en la clase Promocion una variable con el cupo porque sino cada vez que hay que ofrecerle a un usuario una promocion tendríamos que recorrer las atracciones buscando las atracciones incluidas y esto es mucho mas lento que recorrer las atracciones al momento de crear la promocion para sacar el cupo y luego solo actualizar el cupo en las atracciones y las promociones en caso de que el usuario la aceptó.
- Yo creo que cuando una promocion no tiene cupo la podemos eliminar de la lista.
- Con el precio yo creo que tendría que ser una variable al igua que el cupo porque sino estamos recorriendo todas las atracciones cuando queremos saber el precio de las promociones (en el caso de las del tipo AxB y porcentuales).
- Las atracciones incluidas podría ser una lista de Strings, yo lo había pensado como un hashMap con clave String (nombre de la atraccion) y el campo valor era del tipo Atraccion( que tenia todos los datos de cada una) pero si en la clase promocion tenemos una variable cupo y precio no es necesario esto, con tener el nombre de la atraccion nos alcanza para buscarlas en las atracciones disponibles al momento de crear una promocion o actualizar sus datos.
- Las promociones es importante compararlas para ofrecerlas al usuario, yo creo que en vez de usar el compareTo conviene el comparetor porque las promociones hay que compararlas entre ellas pero en base a la preferencia del usuario por eso yo había creado las clases ComparadorAtracciones y ComparadorPromociones ya que no pude hacelo solo con el compareTo.
- En el caso de usar estas clases convendría que las atracciones y las promocones estén guardadas en una lista porque podemos reordenarla en base a los diferentes usuarios, si fuera un set el criterio de ordenamiento se establce cuando se crea y tendríamos que ir pisando el Set cada vez que cambiamos de usuario si cambia su preferencia.

Clase Recomendador:

- Yo creo que sería util crear esta clase con los atributos Cola de Usuarios, Lista de atracciones, Lista Promociones (puede hacer falta algun otro) y dentro de esta clase tener los metodos que mediante la clase Archivo cargan los datos y manejan los mensajes por consola.
- Una ventaja es que al momento de leer las promociones si ya leimos las atracciones podemos simplificar los datos en el archivo de datos de entrada poniendo solo el nombre de las atracciones que incluye cada promocion y buscando sus datos en la lista de atracciones (atributo privado de la clase) para establecer el cupo y precio segun el tipo de promocion.

**Comment by LuisDiNicco** [comment]
Hola chicos, ahí pude hacer el merge en el main con las cosas que estuve haciendo.
Ahí agregue la función para hacer los archivos de salida y saque un par de métodos que no usábamos.

Cosas que faltarían o que habría que revisar:
1. En las promociones AxB, hacemos la separación de la atracción gratis del resto de atracciones incluidas. En la clase promocion, en los metodos recalcularCupo() y actualizarRecomendaciones() solo trabajamos con las atracciones incluidas y no tenemos en cuenta la gratis. No se si hay algo que no vi o pifiamos ahí.
2. Ver si hay alguna forma de mejorar recalcularCupo(), actualizarRecomendaciones() de la clase Promoción y actualizarRecomendaciones() de Atraccion para no usar tantos for. Capaz usando el mapa de atracciones en vez de la lista podemos ahorrarnos algunos ciclos. 
3. Cuando tengamos el codigo definitivo, empezar a hacer los tests de las clases Atracción, Promoción y Usuario. En la clase Recomendador habría que ver bien como hacer los test porque el único método publico es realizarSugerencia y no es muy testeable.
4. Hacer el video explicando como funciona el programa.
